// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3T7M8BxK7XMStAe0b0VcBXJvxebICkck',
    appId: '1:1063297455736:web:87ff9cd8e1f9c43e887f8d',
    messagingSenderId: '1063297455736',
    projectId: 'habitica-39b0b',
    authDomain: 'habitica-39b0b.firebaseapp.com',
    storageBucket: 'habitica-39b0b.firebasestorage.app',
    measurementId: 'G-L1MBNLH3RZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCapqoqOhMpIO65kttXU983fAPwwNBUbgk',
    appId: '1:1063297455736:android:391361ed1e6a9d24887f8d',
    messagingSenderId: '1063297455736',
    projectId: 'habitica-39b0b',
    storageBucket: 'habitica-39b0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO2voP8J_T2RaVzhRAF7amDBBTjqxOW9M',
    appId: '1:1063297455736:ios:837a92a42ae64057887f8d',
    messagingSenderId: '1063297455736',
    projectId: 'habitica-39b0b',
    storageBucket: 'habitica-39b0b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO2voP8J_T2RaVzhRAF7amDBBTjqxOW9M',
    appId: '1:1063297455736:ios:837a92a42ae64057887f8d',
    messagingSenderId: '1063297455736',
    projectId: 'habitica-39b0b',
    storageBucket: 'habitica-39b0b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3T7M8BxK7XMStAe0b0VcBXJvxebICkck',
    appId: '1:1063297455736:web:013e37294ecbaf6c887f8d',
    messagingSenderId: '1063297455736',
    projectId: 'habitica-39b0b',
    authDomain: 'habitica-39b0b.firebaseapp.com',
    storageBucket: 'habitica-39b0b.firebasestorage.app',
    measurementId: 'G-QE29Y7YS0K',
  );
}
